# Generated by Django 5.2.7 on 2025-10-06 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='dispositivos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_evento', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='AppTomamuestras.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('contenedor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('volumen_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_muestra', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='AppTomamuestras.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('nivel_bateria', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('en_linea', models.BooleanField(default=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('codigo_error', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='AppTomamuestras.dispositivo')),
            ],
        ),
    ]
