# Generated by Django 5.2.7 on 2025-10-06 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTomamuestras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='dispositivos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
